DROP TABLE IF EXISTS AdventureWorksDW2019.dbo.stg_dimemp; 

SELECT EMPLOYEEKEY, FIRSTNAME, LASTNAME, TITLE 
INTO AdventureWorksDW2019.dbo.stg_dimemp 
FROM AdventureWorksDW2019.dbo.DimEmployee 
WHERE EMPLOYEEKEY >= 270 and EMPLOYEEKEY <= 275;

DROP TABLE IF EXISTS AdventureWorksDW2019.dbo.scd_dimemp; 

CREATE TABLE AdventureWorksDW2019.dbo.scd_dimemp 
(EMPLOYEEKEY INT, 
FIRSTNAME NVARCHAR(50),
LASTNAME NVARCHAR(50),
TITLE NVARCHAR(50),
STARTDATE DATETIME,
ENDDATE DATETIME);
